AWSTemplateFormatVersion: "2010-09-09"
# Version 1.0 - Initial version
Parameters:
  SubnetAName:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet Identifier 
  SubnetBName:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet Identifier 
  SubnetCName:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet Identifier 
    Default: ' '
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket
    Default: ised-s3-355322244959-chendy-s3-test
  CFTempateURL:
    Type: String
    Default: https://ised-s3-355322244959-chendy-s3-test.s3.ca-central-1.amazonaws.com/CF/AELB-Lisenter-TargetGroup.yaml
  CFTempateURL2:
    Type: String
    Default: https://ised-s3-355322244959-chendy-s3-test.s3.ca-central-1.amazonaws.com/CF/AELB-certsListener.yaml
  CFTempateURL3:
    Type: String
    Default: https://ised-s3-355322244959-chendy-s3-test.s3.ca-central-1.amazonaws.com/CF/AELB-Lisenter-TargetGroup2.yaml
  TargetTest:
    Type: String
  TargetTest2:
    Type: String    
  NumberOfAz:
    Type: String
    Default: 2
    AllowedPattern: '[2-3]'

Conditions:

  Has3Az: !Equals [ !Ref NumberOfAz, 3 ]

Resources:
    AELB:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Properties:
        LoadBalancerAttributes:
          - Key: access_logs.s3.enabled
            Value: true
          - Key: access_logs.s3.bucket
            # Value: ised-s3-355322244959-chendy-s3-test
            Value: !Ref S3BucketName   
        Name: !Join ['-', [!Ref 'AWS::StackName', 'AELB']]
        Scheme: internal
        Subnets: 
          - !Ref SubnetAName
          - !Ref SubnetBName
          - Fn::If:
            - Has3Az
            - !Ref SubnetCName
            - !Ref AWS::NoValue
        Type: application
    
    TargetAndListener:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: !Ref CFTempateURL
        Parameters:
          # VPCId: !Ref VpcName
          # TargetGroupName: !Ref TargetTest
          AELBarn: !Ref AELB
          ListenerPort: 80
          RedirectingPort1: 443
          RedirectingProtocol: HTTPS
          RedirectinStatusCode1: HTTP_301
          ListenerProtocol: HTTP
      DependsOn: TargetAndListener2   

    TargetAndListener2:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: !Ref CFTempateURL2
        Parameters:
          AELBarn: !Ref AELB
          ListenerPort: 443
          ListenerProtocol: HTTPS
      DependsOn: AELB 
