AWSTemplateFormatVersion: "2010-09-09"
# Version 1.0 - Initial version
Parameters:
  AELBarn:
    Type: String
  ListenerPort:
    Type: String
  RedirectingPort1:
    Type: String
  RedirectingProtocol:
    Type: String    
  RedirectinStatusCode1:
    Type: String
  ListenerProtocol:
    Type: String


Resources:
    LoadBalancerListener:
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
        LoadBalancerArn: !Ref AELBarn
        Port: !Ref ListenerPort
        Protocol: HTTP
        DefaultActions:
          - Type: forward
            TargetGroupArn: !Ref TargetGroup
