AWSTemplateFormatVersion: "2010-09-09"
# Version 1.0 - Initial version
Parameters:
  SubnetAName:
    # Type: AWS::EC2::Subnet::Id
    Type: String
    Description: Subnet Identifier
    Default: subnet-00c09151ad1c9a337
  SubnetBName:
    # Type: AWS::EC2::Subnet::Id
    Type: String
    Description: Subnet Identifier
    Default: subnet-086aefecb074e9932
  SubnetCName:
    # Type: AWS::EC2::Subnet::Id
    Type: String
    Description: Subnet Identifier 
    # Default: 'Not selected'
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket
    Default: ised-s3-787897748034-artur-test-lb-log
  CertsDomainNameParam:
    Type: String
  CFTempateURLDefaultAction:
    Type: String
    Default: https://ised-s3-787897748034-artur-test-lb-log.s3.ca-central-1.amazonaws.com/ck-elb-test/AELB-Listener-Default-Action2.yaml
  NumberOfAz:
    Type: String
    Default: 2
    AllowedPattern: '[2-3]'

Conditions:

  Has3Az: !Equals [ !Ref NumberOfAz, 3 ]

Resources:
    AELB:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Properties:
        LoadBalancerAttributes:
          - Key: access_logs.s3.enabled
            Value: true
          - Key: access_logs.s3.bucket
            Value: !Ref S3BucketName   
        Name: !Join ['-', [!Ref 'AWS::StackName', 'AELB']]
        # Scheme: internal
        Subnets: 
          - !Ref SubnetAName
          - !Ref SubnetBName
          - Fn::If:
            - Has3Az
            - !Ref SubnetCName
            - !Ref AWS::NoValue
        Type: application
    
    ## Should all load balancer have a this default action and listener?
    CreateListener443DefaultFixedResponse:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: !Ref CFTempateURLDefaultAction
        Parameters:
          AELBarn: !Ref AELB
          DefaultType: "fixed-response"
          ListenerPort: 443
          ListenerProtocol: HTTPS
          CertDomainName: !Ref CertsDomainNameParam
          CreateRobotTxtParam: "true"
          RedirectingProtocol: " "
          TargetTypeParam: " "
          TargetGroupPort: " "
          TargetGroupVPCId: " "
          TargetGroupProtocol: " "
          TargetIp: " "
          TargetPortNumber: " "
          RedirectingPort: " "
          TargetGroupName: " "
          PriorityParam: 1

      DependsOn: AELB 
    

Outputs:
  TestCondition:
    Description: Has3Az
    Value:
      !If
      - Has3Az
      - "It Has 3AZ"
      - "Does not have 3Az"