AWSTemplateFormatVersion: "2010-09-09"
# Version 1.0 - Initial version
Parameters:
  AELBarn:
    Type: String
  ListenerPort:
    Type: String
  ListenerProtocol:
    Type: String


Resources:
    LoadBalancerListener:
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
          
        Certificates:
          # - CertificateArn: arn:aws:acm:ca-central-1:355322244959:certificate/31a25bb4-37e5-45d8-a246-0364571e5bb2
          - CertificateArn:  !Ref mycert
         

        LoadBalancerArn: !Ref AELBarn
        Port: !Ref ListenerPort
        Protocol: !Ref ListenerProtocol

        DefaultActions:
         - Type: fixed-response
           FixedResponseConfig: 
            ContentType: text/plain
            # MessageBody: String
            StatusCode: 503
      DependsOn: mycert
    
    # TargetGroup:
    #   Type: AWS::ElasticLoadBalancingV2::TargetGroup
    #   Properties:
    #     Name: !Join ['-', [TargetGroupName,'Target-group']]
    #     VpcId: !Ref VPCId
    #     Port: 443
    #     Protocol: HTTPS
    #     TargetType: instance
    #     Targets:
    #       - Id: i-04322a19cfb951d5e
    #         Port: 443


    mycert:
      Type: AWS::CertificateManager::Certificate
      # Condition: CreateCerts
      Properties:
        DomainName: ck.ised-isde.canada.ca
        ValidationMethod: DNS