AWSTemplateFormatVersion: "2010-09-09"
# Version 1.0 - Initial version
Parameters:
  Name:
    Type: String
  Environment:
    Type: String
  SubnetAName:
    # Type: AWS::EC2::Subnet::Id
    Type: String
    Description: Public Subnet Identifier
  SubnetBName:
    # Type: AWS::EC2::Subnet::Id
    Type: String
    Description: Public Subnet Identifier
  SubnetCName:
    # Type: AWS::EC2::Subnet::Id
    Type: String
    Description: Public Subnet Identifier
    # Default: 'Not selected'
  CertsArnParam:
    Type: String    
  NumberOfAz:
    Type: String
    Default: 2
    AllowedPattern: '[2-3]'
  S3BucketNamePrefix:
    Type: AWS::SSM::Parameter::Value<String>
    Default: S3BucketNamePrefix
  AccountIDLog:
    Type: AWS::SSM::Parameter::Value<String>
    Default: AccountIDLog

Conditions:

  Has3Az: !Equals [ !Ref NumberOfAz, 3 ]

Resources:
    AELB:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Properties:
        LoadBalancerAttributes:
          - Key: access_logs.s3.enabled
            Value: true
          - Key: access_logs.s3.bucket
            Value: !Join ['-', [!Ref S3BucketNamePrefix, !Ref AccountIDLog, "logs-lb"]]   
        Name: !Join ['-', ["alb", !Ref "AWS::AccountId", !Ref Name,  !Ref "Environment"]]
        Scheme: internal
        Subnets: 
          - !Ref SubnetAName
          - !Ref SubnetBName
          - Fn::If:
            - Has3Az
            - !Ref SubnetCName
            - !Ref AWS::NoValue
        Type: application
    
    CreateListener443DefaultFixedResponse:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: !Join [ '', [!Ref S3Templates, "AELB-Listener-Default-Action.yaml" ]]
        Parameters:
          AELBarn: !Ref AELB
          DefaultType: "fixed-response"
          ListenerPort: 443
          ListenerProtocol: HTTPS
          # CertDomainName: !Ref CertsDomainNameParam
          CertArn: !Ref CertsArnParam
          CreateRobotTxtParam: "true"
          RedirectingProtocol: " "
          TargetTypeParam: " "
          TargetGroupPort: " "
          TargetGroupVPCId: " "
          TargetGroupProtocol: " "
          TargetIp: " "
          TargetPortNumber: " "
          RedirectingPort: " "
          TargetGroupName: " "
          PriorityParam: 1

      DependsOn: AELB 

    CreateListener80DefaultRedirect:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: !Join [ '', [!Ref S3Templates, "AELB-Listener-Default-Action.yaml" ]]
        Parameters:
          AELBarn: !Ref AELB
          DefaultType: "redirect"
          ListenerPort: 80
          ListenerProtocol: HTTP
          CertArn: " "
          CreateRobotTxtParam: "true"
          RedirectingProtocol: "HTTPS"
          TargetTypeParam: " "
          TargetGroupPort: " "
          TargetGroupVPCId: " "
          TargetGroupProtocol: " "
          TargetIp: " "
          TargetPortNumber: " "
          RedirectingPort: "443"
          TargetGroupName: " "
          PriorityParam: 1

      DependsOn: CreateListener443DefaultFixedResponse 