AWSTemplateFormatVersion: "2010-09-09"
# Version 1.0 - Initial version
Description: Config Aggregator, Version 1.0
Resources:
  ConfigurationAggregator:
    Type: 'AWS::Config::ConfigurationAggregator'
    Properties:
      OrganizationAggregationSource:
        RoleArn: >-
          arn:aws:iam::256255698049:role/aws-service-role/organizations.amazonaws.com/AWSServiceRoleForOrganizations
        AwsRegions:
          - ca-central-1
        AllAwsRegions: false
      ConfigurationAggregatorName: Ised-AWS-Config-Aggregator