AWSTemplateFormatVersion: "2010-09-09"
# Version 1.0 - Initial version
Description: Creates ingress and egress VPCs. Version 1.0
Resources:
  ElbVpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "{{resolve:ssm:TemplateVPC:1}}"
      Parameters:
        Name: elb
