AWSTemplateFormatVersion: "2010-09-09"
# Version 1.0 - Initial version
# Version 1.1 - Add Transit Gateway
# Version 1.2 - Add NAT VPC
# Version 1.3 - Add Transit gateway Route Table
# Version 1.4 - Add Application Load Balancers
# Version 1.5 - Cidr Block as parameters
Description: Creates ingress and egress Network. Version 1.5
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: "Network Configuration"
      Parameters:
        - Environment
        - AmazonAsn
    - Label:
        default: "Ingress VPC (with Load Balancers)"
      Parameters:
        - IngressVPCCidrBlockAddress
        - IngressVPCCidrBlockSize
    - Label:
        default: "Egress VPC (with NAT Gateways)"
      Parameters:
        - EgressVPCCidrBlockAddress
        - EgressVPCCidrBlockSize
    ParameterLabels:
      Environment:
        default: Environment
      AmazonAsn:
        default: Amazon Side ASN
      IngressVPCCidrBlockAddress:
        default: Cidr Block for the Ingress VPC
      IngressVPCCidrBlockSize:
        default: Cidr Block Size for the Ingress VPC
      EgressVPCCidrBlockAddress:
        default: Cidr Block for the Egress VPC
      EgressVPCCidrBlockSize:
        default: Cidr Block Size for the Egress VPC
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: 
      - dev
      - uat
      - qa
      - prod
  IngressVPCCidrBlockAddress:
    Type: String
  IngressVPCCidrBlockSize:
    Type: String
    AllowedValues:
    - 24
    - 25
    - 26
    - 27
    - 28
    Default: 26
  EgressVPCCidrBlockAddress:
    Type: String
  EgressVPCCidrBlockSize:
    Type: String
    AllowedValues:
    - 24
    - 25
    - 26
    - 27
    - 28
    Default: 26
  AmazonAsn: # Amazon side BGP ASN
    Type: String
    Description: A private Autonomous System Number (ASN) for the Amazon side of a BGP session.
    MinLength: 5
    MaxLength: 10
    ConstraintDescription: The range is 64512 to 65534 for 16-bit ASNs and 4200000000 to 4294967294 for 32-bit ASNs.
  S3Templates:
    Type: AWS::SSM::Parameter::Value<String>
    Default: S3Templates 
Resources:
  TransitGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join [ '', [!Ref S3Templates, "transit-gateway.yaml" ]]
      Tags:
      - Key: Name
        Value: !Join ['-', [!Ref "AWS::StackName", "transit-gateway" ] ]
      - Key: ised-cost-centre
        Value: cio-rdad
      - Key: ised-project-id
        Value: cops-aws
      - Key: ised-environment
        Value: !Ref Environment
      Parameters:
        Name: "network"
        Environment: !Ref Environment
        AmazonAsn: !Ref AmazonAsn
        AutoAcceptSharedAttachments: "enable"
        DefaultRouteTableAssociation: "disable"
        DefaultRouteTablePropagation: "disable"
        DnsSupport: "enable"
        VpnEcmpSupport: "enable"
  TransitGatewayManagementAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    DependsOn: TransitGateway
    Properties:
      TransitGatewayId: !GetAtt 
          - TransitGateway
          - Outputs.TransitGatewayId
      VpcId:
        Fn::ImportValue: DefaultVPCId
      SubnetIds:
        - Fn::ImportValue: StackSet-AWS-Landing-Zone-SharedServicesAccountVPC-8ece3fe3-06fd-4341-8d91-7a4e3ddb9fd8-PublicSubnet1ID
        - Fn::ImportValue: StackSet-AWS-Landing-Zone-SharedServicesAccountVPC-8ece3fe3-06fd-4341-8d91-7a4e3ddb9fd8-PublicSubnet2ID
      Tags:
        - Key: Name
          Value: !Join ['-', ["tgw-attach", !Ref "AWS::AccountId", "maintenance", !Ref "Environment" ] ]
        - Key: ised-cost-centre
          Value: cio-rdad
        - Key: ised-project-id
          Value: cops-aws
        - Key: ised-environment
          Value: !Ref Environment
  TGWRouteTableAssociation:
    Type: AWS::EC2::TransitGatewayRouteTableAssociation
    DependsOn: TransitGatewayManagementAttachment
    Properties:
      TransitGatewayAttachmentId: !Ref TransitGatewayManagementAttachment
      TransitGatewayRouteTableId: !GetAtt 
        - TransitGateway
        - Outputs.TransitGatewayRouteTable
  TGWRouteTablePropagation:
    Type: AWS::EC2::TransitGatewayRouteTablePropagation
    DependsOn: TransitGatewayManagementAttachment
    Properties:
      TransitGatewayAttachmentId: !Ref TransitGatewayManagementAttachment
      TransitGatewayRouteTableId: !GetAtt 
        - TransitGateway
        - Outputs.TransitGatewayRouteTable
  ElbVpc:
    Type: AWS::CloudFormation::Stack
    DependsOn: TransitGateway
    Properties:
      TemplateURL: !Join [ '', [!Ref S3Templates, "vpc.yaml" ]]
      Tags:
      - Key: Name
        Value: !Join ['-', [!Ref "AWS::StackName", "vpc-elb" ] ]
      - Key: ised-cost-centre
        Value: cio-rdad
      - Key: ised-project-id
        Value: cops-aws
      - Key: ised-environment
        Value: !Ref Environment
      Parameters:
        Name: network-elb
        Structure: Public
        NumberAZ: "2"
        Environment: !Ref Environment
        VPCCidrBlockAddress: !Ref IngressVPCCidrBlockAddress
        VPCCidrBlockSize: !Ref IngressVPCCidrBlockSize
  NatVpc:
    Type: AWS::CloudFormation::Stack
    DependsOn: TransitGateway
    Properties:
      TemplateURL: !Join [ '', [!Ref S3Templates, "vpc.yaml" ]]
      Tags:
      - Key: Name
        Value: !Join ['-', [!Ref "AWS::StackName", "vpc-nat" ] ]
      - Key: ised-cost-centre
        Value: cio-rdad
      - Key: ised-project-id
        Value: cops-aws
      - Key: ised-environment
        Value: !Ref Environment
      Parameters:
        Name: network-nat
        Structure: Public-Private
        NumberAZ: "2"
        Environment: !Ref Environment
        VPCCidrBlockAddress: !Ref EgressVPCCidrBlockAddress
        VPCCidrBlockSize: !Ref EgressVPCCidrBlockSize
  PublicALB:
    Type: AWS::CloudFormation::Stack
    DependsOn: ElbVpc
    Properties:
      TemplateURL: !Join [ '', [!Ref S3Templates, "AELB.yaml" ]]
      Tags:
      - Key: Name
        Value: !Join ['-', [!Ref "AWS::StackName", "alb-public" ] ]
      - Key: ised-cost-centre
        Value: cio-rdad
      - Key: ised-project-id
        Value: cops-aws
      - Key: ised-environment
        Value: !Ref Environment
      Parameters:
        Access: public
        Environment: !Ref Environment
        ISEDProjectId: cops-aws
        CostCentre: cio-rdad
        VPCName: !GetAtt 
          - ElbVpc
          - Outputs.VPC
        SubnetAName: !GetAtt 
          - ElbVpc
          - Outputs.SubnetPubA
        SubnetBName: !GetAtt 
          - ElbVpc
          - Outputs.SubnetPubB
        CertsArnParam: arn:aws:acm:ca-central-1:787897748034:certificate/9ce130e8-db35-4b61-99f2-518fdb5ddca5
        NumberOfAz: "2"
  ISEDALB:
    Type: AWS::CloudFormation::Stack
    DependsOn: ElbVpc
    Properties:
      TemplateURL: !Join [ '', [!Ref S3Templates, "AELB.yaml" ]]
      Tags:
      - Key: Name
        Value: !Join ['-', [!Ref "AWS::StackName", "alb-ised" ] ]
      - Key: ised-cost-centre
        Value: cio-rdad
      - Key: ised-project-id
        Value: cops-aws
      - Key: ised-environment
        Value: !Ref Environment
      Parameters:
        Access: ised
        Environment: !Ref Environment
        ISEDProjectId: cops-aws
        CostCentre: cio-rdad
        VPCName: !GetAtt 
          - ElbVpc
          - Outputs.VPC
        SubnetAName: !GetAtt 
          - ElbVpc
          - Outputs.SubnetPubA
        SubnetBName: !GetAtt 
          - ElbVpc
          - Outputs.SubnetPubB
        CertsArnParam: arn:aws:acm:ca-central-1:787897748034:certificate/9ce130e8-db35-4b61-99f2-518fdb5ddca5
        NumberOfAz: "2"