AWSTemplateFormatVersion: "2010-09-09"
# Version 1.0 - Initial version
# Version 1.1 - Template Updated 
# Version 1.2 - Add Ingress Security Group
Description: Template to create the RDS. Version 1.2
Metadata:
 AWS::CloudFormation::Interface:
   ParameterGroups:
     - Label:
         default: "Engine Options"
       Parameters:
         - RDSSnapshot
         - RDSEngine
         - RDSEngineVersion
     - Label:
         default: "General Settings"
       Parameters:
         - Environment
         - DBIdentifier
         - RDSMasterUserPassword
         - RDSSize
         - RDSStorage
         - RDSMaxStorage
         - VPCId
         - VPCName
         - Ec2IpAddress
     - Label:
         default: "Additional Section"
       Parameters:
         - RDSBackupRetentionPeriod
         - PreferredBackupWindowTime
         - PreferredMaintenanceWindow
         - Schedule
     - Label:
         default: "Tags"
       Parameters:
         - ISEDProjectId
         - CostCentre
Mappings:
  MasterUserNameMap:
    postgres:
      MasterUserName: "postgres"
Parameters:
# ===== Engine Options Section =====
  RDSSnapshot:
    Description: Specify if restoring from snapshot
    Type: String
  RDSEngine:
    Type: String
    Description: Engine Type
    Default: postgres
    AllowedValues: 
      - postgres
  RDSEngineVersion:
    Type: String
    Description: Engine Version
    Default: 11.5
# ===== General Section =====
  Environment:
    Type: String
    Description: Environemnt
    Default: dev
    AllowedValues: 
      - dev
      - uat
      - qa
      - prod
  DBIdentifier:
    Description: DB Instance Identifier
    Type: String
  RDSMasterUserPassword:
    NoEcho: true
    Type: String
    Description: Master Password
    #MinLength: 8
    #MaxLength: 16
    #AllowedPattern: ^[a-zA-Z0-9]*$
  RDSSize:
    Type: String
    Description: DB Instance Class
    Default: db.t3.small
    AllowedValues:
      - db.t3.small
      - db.t3.medium
      - db.t3.large
      - db.t3.xlarge
  RDSStorage:
    Type: String
    Description: Allocated Storage
  RDSMaxStorage:
    Type: String
    Description: Maximum Allocated Storage
  VPCId:
    Type: "AWS::EC2::VPC::Id"
    Description: Virtual Private Cloud
  VPCName:
    Type: String
    Description: Virtual Private Cloud Name (Portion between account id and environemnt)
  Ec2IpAddress:
    Type: String
    Description: IP Address of the EC2 to enable the connection
# ===== Additional Section =====
  RDSBackupRetentionPeriod:
    Type: String
    Description: Backup Retention Period
    Default: <None>
    AllowedValues:
      - <None>
      - 7
      - 30
  PreferredBackupWindowTime:
    # We want this to be 01:00 Canada/Eastern (05:00-06:00 for daylight saving, 06:00-07:00 for standard time)
    # This needs to be changed twice a year for EST/EDT (see: COPS-2174)
    Description: "The time at which backups will be done (select 05:00-06:00 when it's daylight saving, 06:00-07:00 when it's standard time)"
    Type: String
    Default: "05:00-06:00"
    AllowedValues:
      - "05:00-06:00"
      - "06:00-07:00"
  PreferredMaintenanceWindow:
    # We want this to be 03:30 Canada/Eastern (07:30-08:00 for daylight saving, 08:30-09:00 for standard time)
    # This needs to be changed twice a year for EST/EDT (see: COPS-2174)
    Description: "The time at which maintenance will be done (select 07:30-08:00 when it's daylight saving, 08:30-09:00 when it's standard time)"
    Type: String  
    Default: "tue:07:30-tue:08:00"
    AllowedValues:
      - "tue:07:30-tue:08:00"
      - "tue:08:30-tue:09:00"
  Schedule:
    Type: String
    Default: <None>
    AllowedValues:
      - <None>
      - end-of-week-shutdown
      - mon-6am-fri-6pm
      - office-hours
      - 24-7 
# ===== Tags Section =====
  ISEDProjectId:
    Type: String
  CostCentre:
    Type: String
Conditions:
  IsRDSRestore: !Not [ !Equals [ !Ref RDSSnapshot, "" ]]
  IsProd: !Equals [ !Ref Environment, prod ]
  IsSchedule: !Not [!Equals [ !Ref Schedule, <None> ]]
  IsPostgres9: !Equals [ !Select [ 0, !Split [ ".", !Ref RDSEngineVersion ] ], "9" ]
  IsPostgres10: !Equals [ !Select [ 0, !Split [ ".", !Ref RDSEngineVersion ] ], "10" ]
  IsPostgres11: !Equals [ !Select [ 0, !Split [ ".", !Ref RDSEngineVersion ] ], "11" ]
  IsEc2IpAddress: !Not [ !Equals [ !Ref Ec2IpAddress, "" ]]
Resources:
  SecurityGroupRDS:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "RDS Secuirty Group"
      GroupName: !Join ['-', ["secg-rds", !Ref "AWS::AccountId", !Ref DBIdentifier ] ]
      VpcId: !Ref VPCId
      Tags:
      - Key: Name
        Value: !Join ['-', ["sg-rds", !Ref "AWS::AccountId", !Ref DBIdentifier ] ]
      - Key: ised-cost-centre
        Value: !Ref CostCentre
      - Key: ised-project-id
        Value: !Ref ISEDProjectId
      - Key: ised-environment
        Value: !Ref Environment
  IngressPostgres:
    Type: AWS::EC2::SecurityGroupIngress
    Condition: IsEc2IpAddress
    Properties:
      Description: Allow incoming connections from EC2s from VPC to RDS on port 5432 (Postgresql)
      GroupId: !Ref SecurityGroupRDS
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      CidrIp: !Ref Ec2IpAddress
  RDS:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain
    Properties:
      DBInstanceIdentifier: !Ref DBIdentifier
      AllocatedStorage: !Ref RDSStorage
      MaxAllocatedStorage: !Ref RDSMaxStorage
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      DBInstanceClass: !Ref RDSSize
      DeletionProtection: true
      Port: 5432
      StorageType: gp2
      MultiAZ: !If [ IsProd, True, False ]
      BackupRetentionPeriod: !Ref RDSBackupRetentionPeriod
      CopyTagsToSnapshot: true
      DBSnapshotIdentifier: !If [ IsRDSRestore, !Ref RDSSnapshot, !Ref "AWS::NoValue" ]
      MasterUsername: !If [ IsRDSRestore, !Ref "AWS::NoValue", !FindInMap [MasterUserNameMap, !Ref RDSEngine, MasterUserName] ]
      MasterUserPassword: !If [ IsRDSRestore, !Ref "AWS::NoValue", !Ref RDSMasterUserPassword ]
      # Some applications recommend backing up the filesystem and the database
      # at the same time. Here, we match the EBS Backup Window
      # We want this to be 01:00 Canada/Eastern -- need to change the time twice a year
      PreferredBackupWindow: !Ref PreferredBackupWindowTime
      # Maintenance window happens after the backup window, overnight to reduce
      # downtime impact
      # We want this to be 03:30-04:00 Canada/Eastern -- need to change the time twice a year
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
      DBName: !If [ IsRDSRestore, !Ref "AWS::NoValue", !Ref DBIdentifier ]
      Engine: !Ref RDSEngine
      EngineVersion: !Ref RDSEngineVersion
      LicenseModel: postgresql-license
      StorageEncrypted: true
      DBParameterGroupName:
        !If
          - IsPostgres9
          - Fn::ImportValue:
              db-parameter-group-postgres96
          - !If
            - IsPostgres10
            - Fn::ImportValue:
                db-parameter-group-postgres10
            - !If
              - IsPostgres11
              - Fn::ImportValue:
                  db-parameter-group-postgres11
              - !Ref AWS::NoValue
      DBSubnetGroupName:
        Fn::ImportValue: 
          Fn::Sub: "dbsubnet-${VPCName}-${Environment}"
      VPCSecurityGroups: [ !Ref SecurityGroupRDS ]
      Tags:
      - Key: Name
        Value: !Join ['-', ["rds", !Ref "AWS::AccountId", !Ref DBIdentifier, !Ref "Environment" ] ]
      - Key: ised-cost-centre
        Value: !Ref CostCentre
      - Key: ised-project-id
        Value: !Ref ISEDProjectId
      - Key: ised-environment
        Value: !Ref Environment
      - Key: ised-backup
        Value: !If [ IsProd, backup-prod, backup-dev ]
      - !If
        - IsSchedule
        - Key: ised-schedule
          Value: !Ref Schedule
        - !Ref AWS::NoValue
Outputs:
  RDS:
    Description: RDS
    Value: !Ref RDS
    Export:
      Name: !Join ['-', ["rds", !Ref "DBIdentifier", !Ref "Environment" ] ]
  RDSEndpoint:
    Description: RDS Endpoint
    Value: !GetAtt RDS.Endpoint.Address
    Export:
      Name: !Join ['-', ["rds-endpoint", !Ref "DBIdentifier", !Ref "Environment" ] ]
  RDSSecurityGroup:
    Value: !Ref SecurityGroupRDS
