AWSTemplateFormatVersion: "2010-09-09"
# Version 1.0 - Initial version
Description: Template to create the RDS. Version 1.0
Metadata:
 AWS::CloudFormation::Interface:
   ParameterGroups:
     - Label:
         default: "Engine Options"
       Parameters:
         - RDSSnapshot
         - RDSEngine
         - RDSEngineVersion
     - Label:
         default: "General Settings"
       Parameters:
         - Environment
         - JIRAProjectKey
         - RDSMasterUserPassword
         - RDSSize
         - RDSStorage
         - VPCName
     - Label:
         default: "Additional Section"
       Parameters:
         - RDSBackupRetentionPeriod
         - PreferredBackupWindowTime
         - PreferredMaintenanceWindow
         - Schedule
     - Label:
         default: "Tags"
       Parameters:
         - ISEDProjectId
         - CostCentre
Mappings:
  MasterUserNameMap:
    postgres:
      MasterUserName: "postgres"
Parameters:
# ===== Engine Options Section =====
  RDSEngine:
    Type: String
    Description: Engine Type
    Default: postgres
    AllowedValues: 
      - postgres
  RDSEngineVersion:
    Type: String
    Description: Engine Version
    Default: 11.5
# ===== General Section =====
  Environment:
    Type: String
    Description: Environemnt
    Default: dev
    AllowedValues: 
      - dev
      - uat
      - qa
      - prod
  JIRAProjectKey:
    Description: DB Instance Identifier (Should match to JIRA project key)
    Type: String
  RDSMasterUserPassword:
    NoEcho: true
    Type: String
    Description: Master Password
    #MinLength: 8
    #MaxLength: 16
    #AllowedPattern: ^[a-zA-Z0-9]*$
  RDSSize:
    Type: String
    Description: DB Instance Class
    Default: <None>
    AllowedValues:
      - <None>
      - db.t3.small
      - db.t3.medium
      - db.t3.large
      - db.t3.xlarge
  RDSStorage:
    Type: String
    Description: Allocated Storage
  VPCName:
    Type: AWS::EC2::VPC
    Description: Virtual Private Cloud
# ===== Additional Section =====
  RDSBackupRetentionPeriod:
    Type: String
    Description: Backup Retention Period
    Default: <None>
    AllowedValues:
      - <None>
      - 7
      - 30
  PreferredBackupWindowTime:
    # We want this to be 01:00 Canada/Eastern (05:00-06:00 for daylight saving, 06:00-07:00 for standard time)
    # This needs to be changed twice a year for EST/EDT (see: COPS-2174)
    Description: "The time at which backups will be done (select 05:00-06:00 when it's daylight saving, 06:00-07:00 when it's standard time)"
    Type: String
    Default: "05:00-06:00"
    AllowedValues:
      - "05:00-06:00"
      - "06:00-07:00"
  PreferredMaintenanceWindow:
    # We want this to be 03:30 Canada/Eastern (07:30-08:00 for daylight saving, 08:30-09:00 for standard time)
    # This needs to be changed twice a year for EST/EDT (see: COPS-2174)
    Description: "The time at which maintenance will be done (select 07:30-08:00 when it's daylight saving, 08:30-09:00 when it's standard time)"
    Type: String  
    Default: "tue:07:30-tue:08:00"
    AllowedValues:
      - "tue:07:30-tue:08:00"
      - "tue:08:30-tue:09:00"
  DBParameterGroupName:
    Type: AWS::RDS::DBParameterGroup
    Description: DB Parameter Group
  Schedule:
    Type: String
    AllowedValues:
      - no
      - end-of-week-shutdown
      - mon-6am-fri-6pm
      - office-hours
      - 24-7 
  ISEDProjectId:
    Type: String
  CostCentre:
    Type: String
# ===== RDS Section =====
  RDSSnapshot:
    Description: Specify if restoring from snapshot
    Type: String
Conditions:
  IsProd: !Equals [ !Ref Environment, prod ]
  IsSchedule: !Not [!Equals [ !Ref Schedule, no ]]
  IsRDSRestore: !Not [ !Equals [ !Ref RDSSnapshot, "" ]]
  HasRDSParamGroup: !Not [ !Equals [ !Ref DBParameterGroupName, "" ] ]
Resources:
  SecurityGroupRDS:
    Type: AWS::EC2::SecurityGroup
    DeletionPolicy: Retain
    Properties:
      GroupDescription: "RDS Secuirty Group"
      VpcId: 
        Fn::ImportValue: 
          Fn::Sub:  "vpc-${VPCName}-${Environment}"
      Tags:
      - Key: Name
        Value: !Join ['-', ["sg-rds", !Ref "AWS::AccountId", !Ref "JIRAProjectKey" ] ]
      - Key: ised-cost-centre
        Value: !Ref CostCentre
      - Key: ised-project-id
        Value: !Ref ISEDProjectId
      - Key: ised-environment
        Value: !Ref Environment
  RDS:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain
    Properties:
      DBInstanceIdentifier: !Ref JIRAProjectKey
      AllocatedStorage: !Ref RDSStorage
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      DBInstanceClass: !Ref RDSSize
      Port: 5432
      StorageType: gp2
      MultiAZ: !If [ IsProd, True, False ]
      BackupRetentionPeriod: !Ref RDSBackupRetentionPeriod
      CopyTagsToSnapshot: true
      DBSnapshotIdentifier: !If [ IsRDSRestore, !Ref RDSSnapshot, !Ref "AWS::NoValue" ]
      MasterUsername: !If [ IsRDSRestore, !Ref "AWS::NoValue", !FindInMap [MasterUserNameMap, !Ref RDSEngine, MasterUserName] ]
      MasterUserPassword: !If [ IsRDSRestore, !Ref "AWS::NoValue", !Ref RDSMasterUserPassword ]
      # Some applications recommend backing up the filesystem and the database
      # at the same time. Here, we match the EBS Backup Window
      # We want this to be 01:00 Canada/Eastern -- need to change the time twice a year
      PreferredBackupWindow: !Ref PreferredBackupWindowTime
      # Maintenance window happens after the backup window, overnight to reduce
      # downtime impact
      # We want this to be 03:30-04:00 Canada/Eastern -- need to change the time twice a year
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
      DBName: !If [ IsRDSRestore, !Ref "AWS::NoValue", !Ref JIRAProjectKey ]
      Engine: !Ref RDSEngine
      EngineVersion: !Ref RDSEngineVersion
      LicenseModel: postgresql-license
      StorageEncrypted: true
      DBParameterGroupName:
        !If
          - HasRDSParamGroup
          - Fn::ImportValue: !Ref DBParameterGroupName
          - !Ref "AWS::NoValue"
      DBSubnetGroupName:
        Fn::ImportValue: 
          Fn::Sub: "dbsubnet-${VPCName}-${Environment}"
      VPCSecurityGroups: [ !Ref SecurityGroupRDS ]
      Tags:
      - Key: Name
        Value: !Join ['-', ["rds", !Ref "AWS::AccountId", !Ref "JIRAProjectKey", !Ref "Environment" ] ]
      - Key: ised-cost-centre
        Value: !Ref CostCentre
      - Key: ised-project-id
        Value: !Ref ISEDProjectId
      - Key: ised-environment
        Value: !Ref Environment
      - Key: ised-backup
        Value: !If [ IsProd, backup-prod, backup-dev ]
      - !If
        - IsSchedule
        - Key: ised-schedule
          Value: !Ref Schedule
        - !Ref AWS::NoValue

Outputs:
  RDS:
    Description: RDS
    Value: !Ref RDS
    Export:
      Name: !Join ['-', [!Ref "JIRAProjectKey", !Ref "Environment", "rds" ] ]
  RDSEndpoint:
    Description: RDS Endpoint
    Value: !GetAtt RDS.Endpoint.Address
    Export:
      Name: !Join ['-', [!Ref "JIRAProjectKey", !Ref "Environment", "rds-endpoint" ] ]
  RDSSecurityGroup:
    Value: !Ref SecurityGroupRDS
