AWSTemplateFormatVersion: "2010-09-09"
# Version 1.0 - Initial version
Description: Template to create the RDS. Version 1.0
Metadata:
 AWS::CloudFormation::Interface:
   ParameterGroups:
     - Label:
         default: "General"
       Parameters:
         - JIRAProjectKey
         - CostCentre
         - ISEDProjectId
         - Environment
         - Schedule
         - VPCName
     - Label:
         default: "RDS"
       Parameters:
         - RDSSize
         - RDSStorage
         - RDSSnapshot
         - RDSMasterUserPassword
         - RDSBackupRetentionPeriod
Parameters:
# ===== General Section =====
  JIRAProjectKey:
    Type: String
  ISEDProjectId:
    Type: String
  CostCentre:
    Type: String
  Environment:
    Type: String
    Default: dev
    AllowedValues: 
      - dev
      - uat
      - qa
      - prod
  VPCName:
    Type: String
  Schedule:
    Type: String
    AllowedValues:
      - no
      - end-of-week-shutdown
      - mon-6am-fri-6pm
      - office-hours
      - 24-7
# ===== RDS Section =====
  RDSStorage:
    Type: String
  RDSSize:
    Type: String
    Default: <None>
    AllowedValues:
      - <None>
      - db.t3.large
  RDSSnapshot:
    Description: Specify if restoring from snapshot
    Type: String
  RDSEngine:
    Type: String
    Default: postgres
  RDSEngineVersion:
    Type: String
    Default: 10.6
  RDSBackupRetentionPeriod:
    Type: String
    Default: <None>
    AllowedValues:
      - <None>
      - 7
      - 30
  RDSMasterUserPassword:
    NoEcho: true
    Type: String
    #MinLength: 8
    #MaxLength: 16
    #AllowedPattern: ^[a-zA-Z0-9]*$
Conditions:
  IsProd: !Equals [ !Ref Environment, prod ]
  IsSchedule: !Not [!Equals [ !Ref Schedule, no ]]
  IsRDSRestore: !Not [ !Equals [ !Ref RDSSnapshot, "" ]]
Resources:
  SecurityGroupRDS:
    Type: AWS::EC2::SecurityGroup
    DeletionPolicy: Retain
    Properties:
      GroupDescription: "RDS Secuirty Group"
      VpcId: 
        Fn::ImportValue: 
          Fn::Sub:  "vpc-${VPCName}-${Environment}"
      Tags:
      - Key: Name
        Value: !Join ['-', ["sg-rds", !Ref "AWS::AccountId", !Ref "JIRAProjectKey" ] ]
      - Key: ised-cost-centre
        Value: !Ref CostCentre
      - Key: ised-project-id
        Value: !Ref ISEDProjectId
      - Key: ised-environment
        Value: !Ref Environment
  RDS:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain
    Properties:
      DBInstanceIdentifier: !Ref JIRAProjectKey
      AllocatedStorage: !Ref RDSStorage
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      DBInstanceClass: !Ref RDSSize
      Port: 5432
      StorageType: gp2
      MultiAZ: !If [ IsProd, True, False ]
      BackupRetentionPeriod: !Ref RDSBackupRetentionPeriod
      CopyTagsToSnapshot: true
      DBSnapshotIdentifier: !If [ IsRDSRestore, !Ref RDSSnapshot, !Ref "AWS::NoValue" ]
      MasterUsername: !If [ IsRDSRestore, !Ref "AWS::NoValue", !Ref JIRAProjectKey ]
      MasterUserPassword: !If [ IsRDSRestore, !Ref "AWS::NoValue", !Ref RDSMasterUserPassword ]
      # Some applications recommend backing up the filesystem and the database
      # at the same time. Here, we match the EBS Backup Window
      PreferredBackupWindow: 06:00-07:00 # UTC
      # Maintenance window happens after the backup window, overnight to reduce
      # downtime impact
      PreferredMaintenanceWindow: tue:08:30-tue:09:00 # UTC
      DBName: !If [ IsRDSRestore, !Ref "AWS::NoValue", !Ref JIRAProjectKey ]
      Engine: !Ref RDSEngine
      EngineVersion: !Ref RDSEngineVersion
      LicenseModel: postgresql-license
      StorageEncrypted: true
      DBSubnetGroupName:
        Fn::ImportValue: 
          Fn::Sub: "dbsubnet-${VPCName}-${Environment}"
      VPCSecurityGroups: [ !Ref SecurityGroupRDS ]
      Tags:
      - Key: Name
        Value: !Join ['-', ["rds", !Ref "AWS::AccountId", !Ref "JIRAProjectKey", !Ref "Environment" ] ]
      - Key: ised-cost-centre
        Value: !Ref CostCentre
      - Key: ised-project-id
        Value: !Ref ISEDProjectId
      - Key: ised-environment
        Value: !Ref Environment
      - Key: ised-backup
        Value: !If [ IsProd, backup-prod, backup-dev ]
      - !If
        - IsSchedule
        - Key: ised-schedule
          Value: !Ref Schedule
        - !Ref AWS::NoValue

Outputs:
  RDS:
    Description: RDS
    Value: !Ref RDS
    Export:
      Name: !Join ['-', [!Ref "JIRAProjectKey", !Ref "Environment", "rds" ] ]
  RDSEndpoint:
    Description: RDS Endpoint
    Value: !GetAtt RDS.Endpoint.Address
    Export:
      Name: !Join ['-', [!Ref "JIRAProjectKey", !Ref "Environment", "rds-endpoint" ] ]
  RDSSecurityGroup:
    Value: !Ref SecurityGroupRDS
