AWSTemplateFormatVersion: "2010-09-09"
Description: Template to create the infrastructure for GPC Risk Management project

Metadata:
 AWS::CloudFormation::Interface:
   ParameterGroups:
     - Label:
         default: "Network Definition"
       Parameters:
         - VPCId
         - VPCName
         - SubnetId
         - Environment
     - Label:
         default: "EC2 Configuration"
       Parameters:
         - EC2OS
         - RootVolumeSize
     - Label:
         default: "RDS Configuration"
       Parameters:
         - DBIdentifier
         - RDSMasterUserPassword
         - RDSEngine
         - RDSEngineVersion
         - RDS Size
         - RDSStorage
         - RDSMaxStorage
         - Ec2IpAddress
     - Label:
         default: "Tags"
       Parameters:
         - ISEDProjectId
         - CostCentre


Parameters:
  S3Templates:
    Type: AWS::SSM::Parameter::Value<String>
    Default: S3Templates
  VPCId:
    Type: "AWS::EC2::VPC::Id"
    Description: Virtual Private Cloud
  VPCName:
    Type: String
    Default: ised
  SubnetId:
    Type: AWS::EC2::Subnet::Id
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
  # ===== EC2 Section =====
  EC2OS:
    Type: String
    Default: Linux
    AllowedValues:
      - Linux
      - Windows-2016
  EC2RootVolumeSize:
    Type: String
    Default: 8
  # ===== EBS Volumes =====
  EBSVolumeSize:
    Type: String
    Default: 2
  EBSVolumeMount:
    Type: String
    Default: /dev/sdg
  # ===== RDS Section =====
  DBIdentifier:
    Type: String
  RDSMasterUserPassword:
    NoEcho: true
    Type: String
  RDSEngine:
    Type: String
    Description: Engine Type
    Default: postgres
    AllowedValues: 
      - postgres
  RDSEngineVersion:
    Type: String
    Description: Engine Version
    Default: 11.5
  RDSSize:
    Type: String
    Default: db.t3.small
    AllowedValues:
      - db.t3.small
      - db.t3.medium
      - db.t3.large
      - db.t3.xlarge
  RDSStorage:
    Type: String
    Default: 20
  RDSMaxStorage:
    Type: String
    Default: 20
  Ec2IpAddress:
    Type: String
  # ===== Tags Section =====
  ISEDProjectId:
    Type: String
    Default: ccots-cops
  CostCentre:
    Type: String
    Default: cio-rdad

  EC2DataVolumeSize:
    Type: String
    Default: 20
  EC2DataVolumeMount:
    Type: String
    Default: /dev/sdf



  EC2Ami:
    Type: String
    Description: Specify if restoring from Ami, otherwise leave blank


  # ===== RDS Section =====
  RDSSnapshot:
    Description: Specify if restoring from snapshot
    Type: String

Conditions:
  IsProd: !Equals [ !Ref Environment, prod ]
  IsEC2Restore: !Equals [ !Ref EC2Ami, "" ]
  IsRDSRestore: !Equals [ !Ref RDSSnapshot, "" ]

Resources:
  EC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join [ '', [!Ref S3Templates, "ec2.yaml" ]]
      Parameters:
        # ===== General Section =====
        VPCId: !Ref VPCId
        SubnetId: !Ref SubnetId
        Environment: !Ref Environment


         # ===== General Section =====
        Schedule: !If [ IsProd, 24-7, office-hours ]

        # ===== EC2 Section =====
        CreateEC2: EC2OS
        EC2Size: t3.large
        EC2Ami: !Ref EC2Ami
        EC2RootVolumeSize: !Ref EC2RootVolumeSize
        # ===== Tags =====
        ISEDProjectId: !Ref ISEDProjectId
        CostCentre: !Ref CostCentre
  RDS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join [ '', [!Ref S3Templates, "rds.yaml" ]]
      Parameters:
        # ===== General Section =====
        VPCId: !Ref VPCId
        VPCName: !Ref VPCName
        Environment: !Ref Environment
        # ===== RDS Section =====
        RDSEngine: !Ref RDSEngine
        RDSEngineVersion: !Ref RDSEngineVersion
        DBIdentifier: !Ref DBIdentifier
        RDSMasterUserPassword: !Ref RDSMasterUserPassword
        RDSStorage: !Ref RDSStorage
        RDSMaxStorage: !Ref RDSMaxStorage
        RDSSize: !Ref RDSSize
        Ec2IpAddress: !Ref Ec2IpAddress
        # ===== Parameters =====
        RDSSnapshot: !Ref RDSSnapshot
        Schedule: !If [ IsProd, 24-7, office-hours ]
        RDSBackupRetentionPeriod: !If [ IsProd, 30, 7 ]
        # ===== Tags =====
        ISEDProjectId: !Ref ISEDProjectId
        CostCentre: !Ref CostCentre

