AWSTemplateFormatVersion: "2010-09-09"
# Version 1.2 - Updating AWS Backup Plan from monthly to weekly (i.e. every Tuesday)
# Version 1.3 - Fixed cron expression for scheduled AWS Backup Plan
# Version 1.4 - Updated AWS Backup Plan time to 8:00 AM (local)
# Version 1.5 - Extract IAM roles and put them in roles.yaml template 
# Version 1.6 - Removed LifeCycle Manager Policies and replaced them with AWS Backup
# Version 1.7 - Changed backup tags and made distinction for OCP specific backups
# Version 1.8 - Remove all Backup Plans/Resources, Keep ONLY Backup Vault and Backup Role for Backup OU implementation
Description: Template to create backup vault and backup role to use AWS Backup for (RDS/EBS) Backup OU implementation strategy. Version 1.8

Resources:
  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "Encryption key for daily"
      EnableKeyRotation: True
      Enabled: True
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal: {AWS: { "Fn::Sub": "arn:aws:iam::${AWS::AccountId}:root" }}
          Action: kms:*
          Resource: "*"
  BackupVault:
    Type: "AWS::Backup::BackupVault"
    Properties:
      BackupVaultName: "DefaultBackupVault01"
      EncryptionKeyArn: !GetAtt KMSKey.Arn

  BackupRole:
    Type: AWS::IAM::Role
    Description: Provides AWS Backup permission to create backups and perform restores on your behalf across AWS services.
    Properties:
      RoleName: ised-backup-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - backup.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup
        - arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForRestores
      Path: /

Outputs:
  BackupVault:
    Description: BackupVault where AWS Backups are stored 
    Value: !Ref BackupVault
  BackupRole:
    Description: Backup Role
    Value: !Ref BackupRole