AWSTemplateFormatVersion: "2010-09-09"
# Version 1.0 - Initial version
# Version 1.1 - Added S3 bucket and Cots account parameter.
# Version 1.2 - Added parameter that relate to Jira and AWS Account id
# Version 1.3 - Added parameters for IT Security and ISED Cloud mailboxes
Parameters:
  VPCFlowLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties: 
      LogGroupName: !Join ['-', ["vpc-flow-log-group", !Ref "AWS::AccountId" ]]
      RetentionInDays: 30