AWSTemplateFormatVersion: "2010-09-09"
# Version 1.0 - Initial version, includes Cost tag, Backup Tag
# Version 1.1 - Fixing initial template
# Version 1.2 - Add Mandatory Tags for patching
# Version 1.3 - Add Jira Automation
# Version 1.3.1 - Fix error in patching rule definition
# Version 1.3.2 - Remove noEcho from Jira Password
# Version 1.3.3 - Remove Network Interface from Cost Rule
# Version 1.3.4 - Remove Route Table, Security Group and Network Acl from Cost Rule
# Version 1.3.5 - Remove Cost Rule from ApiStore, OpenShift, Students, Sandbox Increase the number of retries for jira to 10
# Version 1.3.6 - Remove Patching From OpenShift Account
# Version 1.3.7 - Fixing auto remediation on/off
# Version 1.3.8 - Remove Certificate from Costing config
# Version 1.4 - Add Metadata
Description: Template to create all required config rules. Version 1.4
Metadata:
 AWS::CloudFormation::Interface:
   ParameterGroups:
     - Label:
         default: "Jira"
       Parameters:
         - IsedJiraUrl
         - IsedJiraUserName
         - IsedJiraProject
         - IsedJiraPassword
     - Label:
         default: "Costing"
       Parameters:
         - IsedCostCentre
         - IsedEnvironment
         - IsedProjectId
     - Label:
         default: "Backup"
       Parameters:
         - IsedBackup
     - Label:
         default: "Patch"
       Parameters:
         - IsedPatch
Conditions:
  IsRemediationOn: !And [!Not [!Equals [ !Ref "AWS::AccountId", 355322244959 ]], !Not [!Equals [ !Ref "AWS::AccountId", 593927778252 ]]]
  IsCostRuleOn: !And [!Not [!Equals [ !Ref "AWS::AccountId", 803354934415 ]] , !Not [!Equals [ !Ref "AWS::AccountId", 870005858651 ]], !Not [!Equals [ !Ref "AWS::AccountId", 501108984960 ]]]
  IsPatchingRuleOn: !Not [!Equals [ !Ref "AWS::AccountId", 870005858651 ]]
Parameters:
  IsedCostCentre:
    Type: String
  IsedProjectId:
    Type: String
  IsedEnvironment:
    Type: String
  IsedBackup:
    Type: String
  IsedPatch:
    Type: String
  IsedJiraUrl:
    Type: String
  IsedJiraUserName:
    Type: String
  IsedJiraProject:
    Type: String
  IsedJiraPassword:
    Type: String
    NoEcho: true
Resources:
  BasicParameterJiraPassword:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: ised-jira-password
      Type: String
      Value: !Ref IsedJiraPassword
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ised-lambda-execution-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
        - arn:aws:iam::aws:policy/AWSLambdaExecute
      Path: /
  AutomationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ised-automation-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - ssm.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonSSMAutomationRole
      Path: /
      Policies:
       - PolicyName: "root"
         PolicyDocument:
           Version: "2012-10-17"
           Statement:
             - Effect: "Allow"
               Action: 
               - "lambda:*"
               - "iam:PassRole"
               Resource: "*"
  AWSConfigRuleTagsCost:
    Type: AWS::Config::ConfigRule
    Condition: IsCostRuleOn
    Properties:
      ConfigRuleName: "ised-mandatory-tags-cost"
      Description: Checks whether your resources have the tags that you specify.
      InputParameters:
        tag1Key: ised-cost-centre
        tag1Value: !Ref IsedCostCentre
        tag2Key: ised-project-id
        tag2Value: !Ref IsedProjectId
        tag3Key: ised-environment
        tag3Value: !Ref IsedEnvironment
      Scope:
        ComplianceResourceTypes:
        - AWS::ACM::Certificate
        - AWS::AutoScaling::AutoScalingGroup
        # - AWS::CloudFormation::Stack
        # - AWS::CodeBuild::Project
        - AWS::DynamoDB::Table
        - AWS::EC2::CustomerGateway
        - AWS::EC2::Instance
        - AWS::EC2::InternetGateway
        # - AWS::EC2::NetworkAcl
        # - AWS::EC2::NetworkInterface
        # - AWS::EC2::RouteTable
        # - AWS::EC2::SecurityGroup
        - AWS::EC2::Subnet
        - AWS::EC2::Volume
        - AWS::EC2::VPC
        - AWS::EC2::VPNConnection
        - AWS::EC2::VPNGateway
        - AWS::ElasticLoadBalancing::LoadBalancer
        - AWS::ElasticLoadBalancingV2::LoadBalancer
        - AWS::RDS::DBInstance
        - AWS::RDS::DBSecurityGroup
        - AWS::RDS::DBSnapshot
        - AWS::RDS::DBSubnetGroup
        - AWS::RDS::EventSubscription
        - AWS::Redshift::Cluster
        - AWS::Redshift::ClusterParameterGroup
        - AWS::Redshift::ClusterSecurityGroup
        - AWS::Redshift::ClusterSnapshot
        - AWS::Redshift::ClusterSubnetGroup
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: REQUIRED_TAGS
  AWSConfigRuleTagsBackup:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: "ised-mandatory-tags-backup"
      Description: Checks whether your resources have the tags that you specify.
      InputParameters:
        tag1Key: ised-backup
        tag1Value: !Ref IsedBackup
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::Volume
        - AWS::RDS::DBInstance
      Source:
        Owner: AWS
        SourceIdentifier: REQUIRED_TAGS
  AWSConfigRuleTagsPatching:
    Type: AWS::Config::ConfigRule
    Condition: IsPatchingRuleOn
    Properties:
      ConfigRuleName: "ised-mandatory-tags-patching"
      Description: Checks whether your resources have the tags that you specify.
      InputParameters:
        tag1Key: Patch Group
        tag1Value: !Ref IsedPatch
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::Instance
      Source:
        Owner: AWS
        SourceIdentifier: REQUIRED_TAGS
  BasicRemediationConfigurationTagsCost:
    Type: "AWS::Config::RemediationConfiguration"
    Condition: IsCostRuleOn
    Properties:
      ConfigRuleName: !Ref AWSConfigRuleTagsCost
      Parameters:
        AutomationAssumeRole:
          StaticValue:
            Values: 
            - Fn::GetAtt: [ AutomationRole, Arn ]
        IssueDescription:
          ResourceValue:
            Value: RESOURCE_ID
        IssueSummary:
          StaticValue:
            Values:
            - !Join ['-', ["AWS Config", !Ref "AWS::AccountId",  !Ref AWSConfigRuleTagsCost ] ]
        IssueTypeName:
          StaticValue:
            Values:
            - Task
        JiraURL:
          StaticValue:
            Values:
            - !Ref IsedJiraUrl
        JiraUsername:
          StaticValue:
            Values:
            - !Ref IsedJiraUserName
        LambdaAssumeRole:
          StaticValue:
            Values:
            - Fn::GetAtt: [ LambdaRole, Arn ]
        ProjectKey:
          StaticValue:
            Values:
            - !Ref IsedJiraProject
        SSMParameterName:
          StaticValue:
            Values:
            - ised-jira-password
      TargetId: "AWS-CreateJiraIssue"
      TargetType: "SSM_DOCUMENT"
      Automatic: !If [ IsRemediationOn, true, false ]
      MaximumAutomaticAttempts: 10
      RetryAttemptSeconds: 60
  BasicRemediationConfigurationTagsBackup:
    Type: "AWS::Config::RemediationConfiguration"
    Properties:
      ConfigRuleName: !Ref AWSConfigRuleTagsBackup
      Parameters:
        AutomationAssumeRole:
          StaticValue:
            Values: 
            - Fn::GetAtt: [ AutomationRole, Arn ]
        IssueDescription:
          ResourceValue:
            Value: RESOURCE_ID
        IssueSummary:
          StaticValue:
            Values:
            - !Join ['-', ["AWS Config", !Ref "AWS::AccountId",  !Ref AWSConfigRuleTagsBackup ] ]
        IssueTypeName:
          StaticValue:
            Values:
            - Task
        JiraURL:
          StaticValue:
            Values:
            - !Ref IsedJiraUrl
        JiraUsername:
          StaticValue:
            Values:
            - !Ref IsedJiraUserName
        LambdaAssumeRole:
          StaticValue:
            Values:
            - Fn::GetAtt: [ LambdaRole, Arn ]
        ProjectKey:
          StaticValue:
            Values:
            - !Ref IsedJiraProject
        SSMParameterName:
          StaticValue:
            Values:
            - ised-jira-password
      TargetId: "AWS-CreateJiraIssue"
      TargetType: "SSM_DOCUMENT"
      Automatic: !If [ IsRemediationOn, true, false ]
      MaximumAutomaticAttempts: 10
      RetryAttemptSeconds: 60
  BasicRemediationConfigurationTagsPatching:
    Type: "AWS::Config::RemediationConfiguration"
    Condition: IsPatchingRuleOn
    Properties:
      ConfigRuleName: !Ref AWSConfigRuleTagsPatching
      Parameters:
        AutomationAssumeRole:
          StaticValue:
            Values: 
            - Fn::GetAtt: [ AutomationRole, Arn ]
        IssueDescription:
          ResourceValue:
            Value: RESOURCE_ID
        IssueSummary:
          StaticValue:
            Values:
            - !Join ['-', ["AWS Config", !Ref "AWS::AccountId",  !Ref AWSConfigRuleTagsPatching ] ]
        IssueTypeName:
          StaticValue:
            Values:
            - Task
        JiraURL:
          StaticValue:
            Values:
            - !Ref IsedJiraUrl
        JiraUsername:
          StaticValue:
            Values:
            - !Ref IsedJiraUserName
        LambdaAssumeRole:
          StaticValue:
            Values:
            - Fn::GetAtt: [ LambdaRole, Arn ]
        ProjectKey:
          StaticValue:
            Values:
            - !Ref IsedJiraProject
        SSMParameterName:
          StaticValue:
            Values:
            - ised-jira-password
      TargetId: "AWS-CreateJiraIssue"
      TargetType: "SSM_DOCUMENT"
      Automatic: !If [ IsRemediationOn, true, false ]
      MaximumAutomaticAttempts: 10
      RetryAttemptSeconds: 60            