AWSTemplateFormatVersion: "2010-09-09"
# Version 1.0 - Initial version
# Version 1.1 - Add Admin role trust with master
# Version 1.2 - Add Nexus role for cots account
Description: Template to create all required roles. Version 1.2
Conditions:
  IsNotMaster: !Not [!Equals [ !Ref "AWS::AccountId", 256255698049 ]]
  IsCotsAccount: !Equals [ !Ref "AWS::AccountId", 850605615431 ]
Resources:
  NexusRole:
    Type: AWS::IAM::Role
    Condition: IsCotsAccount
    Properties:
      RoleName: ised-nexus-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        # Role for patching
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        # Role for Cloudwatch
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy  
  NexusVolumeTaggingPolicy:
    Type: AWS::IAM::Policy
    Condition: IsCotsAccount
    Properties:
      Roles: !Ref NexusRole
      PolicyName: ised-nexus-volume-tagging-policy
      # Permissions for the EC2 to tag the volumes (ex: root) from User Data
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            "Action":
              - "ec2:CreateTags"
            Resource:
              - "arn:aws:ec2:*:*:instance/*"
              - "arn:aws:ec2:*:*:volume/*"
          - Effect: "Allow"
            Action: "ec2:DescribeInstances"
            Resource: "*"
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Condition: IsCotsAccount
    Properties:
      InstanceProfileName: ised-nexus-ec2-instance-profile
      Roles: !Ref NexusRole
  IsedAdminRole:
    Type: AWS::IAM::Role
    Condition: IsNotMaster
    DeletionPolicy: Retain
    Properties:
      RoleName: ised-admin-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: {AWS: 256255698049}
          Action: ['sts:AssumeRole']
      Path: "/"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AdministratorAccess  
      Tags:
        - Key: Name
          Value: !Join ['-', ["role", !Ref "AWS::AccountId", ised-admin-role ] ]
        - Key: ised-cost-centre
          Value: cio-rdad
        - Key: ised-project-id
          Value: cops-aws
        - Key: ised-environment
          Value: ops
  LambdaExecutionRole:
    Description: roles CF. Used by VPC template to calculate subnet sizes
    Type: AWS::IAM::Role
    Properties:
      RoleName: ised-vpc-lambda-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: {Service: [lambda.amazonaws.com]}
          Action: ['sts:AssumeRole']
      Path: "/"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
        - Key: Name
          Value: !Join ['-', ["role", !Ref "AWS::AccountId", ised-vpc-lambda-execution-role ] ]
        - Key: ised-cost-centre
          Value: cio-rdad
        - Key: ised-project-id
          Value: cops-aws
        - Key: ised-environment
          Value: ops
  VPCFlowLogRole:
    Description: roles CF. Used by VPC template send logs to cloud watch
    Type: AWS::IAM::Role
    Properties:
      RoleName: ised-vpc-flow-log-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal: {Service: [vpc-flow-logs.amazonaws.com]}
          Action: ['sts:AssumeRole']
      Policies:
      - PolicyName: "VPCFlowLogsRole"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:DescribeLogGroups"
              - "logs:DescribeLogStreams"
              - "logs:PutLogEvents"
            Resource: "*" 
      Tags:
        - Key: Name
          Value: !Join ['-', ["role", !Ref "AWS::AccountId", ised-vpc-flow-log-role ] ]
        - Key: ised-cost-centre
          Value: cio-rdad
        - Key: ised-project-id
          Value: cops-aws
        - Key: ised-environment
          Value: ops
  ConfigLambdaRole:
    Description: This role is used by the lambda function "Ised-CreateJiraIssue"
    Type: AWS::IAM::Role
    Properties:
      RoleName: ised-config-lambda-execution-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/ResourceGroupsandTagEditorReadOnlyAccess
      Path: /
  AutomationRole:
    Type: AWS::IAM::Role
    Description: This role is used by the SSM document to invoke the lambda function "Ised-CreateJiraIssue"
    Properties:
      RoleName: ised-config-automation-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - ssm.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonSSMAutomationRole
      Path: /
      Policies:
       - PolicyName: "root"
         PolicyDocument:
           Version: "2012-10-17"
           Statement:
             - Effect: "Allow"
               Action: 
               - "lambda:*"
               - "iam:PassRole"
               Resource: "*"
Outputs:
  RoleLambdaExecution:
    Description: LambdaExecutionRole
    Value: !GetAtt LambdaExecutionRole.Arn
    Export: 
      Name: LambdaExecutionRole
  RoleVPCFlowLog:
    Description: VPCFlowLogRole
    Value: !GetAtt VPCFlowLogRole.Arn
    Export: 
      Name: VPCFlowLogRole
  RoleAdmin:
    Condition: IsNotMaster
    Description: IsedAdminRole
    Value: !GetAtt IsedAdminRole.Arn
    Export: 
      Name: IsedAdminRole
  ConfigLambdaRole:
    Description: ConfigLambdaRole
    Value: !GetAtt ConfigLambdaRole.Arn
    Export: 
      Name: ConfigLambdaRole
  AutomationRole:
    Description: AutomationRole
    Value: !GetAtt AutomationRole.Arn
    Export: 
      Name: AutomationRole
  NexusRole:
    Description: NexusRole
    Value: !GetAtt NexusRole.Arn
    Export: 
      Name: NexusRole
  NexusVolumeTaggingPolicy:
    Description: NexusVolumeTaggingPolicy
    Value: !GetAtt NexusVolumeTaggingPolicy.Arn
    Export: 
      Name: NexusVolumeTaggingPolicy
  EC2InstanceProfile:
    Description: EC2InstanceProfile
    Value: !GetAtt EC2InstanceProfile.Arn
    Export: 
      Name: EC2InstanceProfile
