AWSTemplateFormatVersion: "2010-09-09"
# Version 1.0 - Initial version
# Version 1.1 - Add Admin role trust with master
# Version 1.2 - Add Nexus role for cots account
# Version 1.3 - Added Backup role and DataLifeCycleManager role for RDS and EBS backups
#             - Added 'Condtion' in 'Outputs' section related to NexusRole, otherwise deployment fails
# Version 1.4 - Add generic ised-managed-instance-role with SSM and S3 permissions for EC2 patching
# Version 1.5 - Update to use Parameter Store
Description: Template to create all required roles. Version 1.5
Conditions:
  IsNotMaster: !Not [!Equals [ !Ref "AWS::AccountId", !Ref AccountIDMaster ]]

Parameters:
  AccountIDMaster:
    Type: AWS::SSM::Parameter::Value<String>
    Default: AccountIDMaster

Resources:
  ManagedInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ised-managed-instance-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        # Role for patching
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  ManagedInstancePolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref ManagedInstanceRole
      PolicyName: ised-managed-instance-policy
      # Permissions for the EC2 to write to the patching s3 bucket
      # See: https://docs.aws.amazon.com/systems-manager/latest/userguide/setup-instance-profile.html#instance-profile-custom-s3-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:GetObject"
            Resource:
              - "arn:aws:s3:::aws-ssm-ca-central-1/*"
              - "arn:aws:s3:::aws-windows-downloads-ca-central-1/*"
              - "arn:aws:s3:::amazon-ssm-ca-central-1/*"
              - "arn:aws:s3:::amazon-ssm-packages-ca-central-1/*"
              - "arn:aws:s3:::ca-central-1-birdwatcher-prod/*"
              - "arn:aws:s3:::patch-baseline-snapshot-ca-central-1/*"
          - Effect: "Allow"
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:PutObjectAcl"
              - "s3:GetEncryptionConfiguration"
            Resource:
              - !Join ['', ["arn:aws:s3:::", "{{resolve:ssm:S3BucketNamePrefix:1}}", "-", !Ref "AWS::AccountId", "-ec2patching/*" ]]
              - !Join ['', ["arn:aws:s3:::", "{{resolve:ssm:S3BucketNamePrefix:1}}", "-", !Ref "AWS::AccountId", "-ec2patching/" ]]
  ManagedInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: ised-managed-instance-profile
      Roles:
        - !Ref ManagedInstanceRole
  IsedAdminRole:
    Type: AWS::IAM::Role
    Condition: IsNotMaster
    DeletionPolicy: Retain
    Properties:
      RoleName: ised-admin-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: {AWS: 256255698049}
          Action: ['sts:AssumeRole']
      Path: "/"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AdministratorAccess  
      Tags:
        - Key: Name
          Value: !Join ['-', ["role", !Ref "AWS::AccountId", ised-admin-role ] ]
        - Key: ised-cost-centre
          Value: cio-rdad
        - Key: ised-project-id
          Value: cops-aws
        - Key: ised-environment
          Value: ops
  LambdaExecutionRole:
    Description: roles CF. Used by VPC template to calculate subnet sizes
    Type: AWS::IAM::Role
    Properties:
      RoleName: ised-vpc-lambda-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: {Service: [lambda.amazonaws.com]}
          Action: ['sts:AssumeRole']
      Path: "/"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
        - Key: Name
          Value: !Join ['-', ["role", !Ref "AWS::AccountId", ised-vpc-lambda-execution-role ] ]
        - Key: ised-cost-centre
          Value: cio-rdad
        - Key: ised-project-id
          Value: cops-aws
        - Key: ised-environment
          Value: ops
  VPCFlowLogRole:
    Description: roles CF. Used by VPC template send logs to cloud watch
    Type: AWS::IAM::Role
    Properties:
      RoleName: ised-vpc-flow-log-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal: {Service: [vpc-flow-logs.amazonaws.com]}
          Action: ['sts:AssumeRole']
      Policies:
      - PolicyName: "VPCFlowLogsRole"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:DescribeLogGroups"
              - "logs:DescribeLogStreams"
              - "logs:PutLogEvents"
            Resource: "*" 
      Tags:
        - Key: Name
          Value: !Join ['-', ["role", !Ref "AWS::AccountId", ised-vpc-flow-log-role ] ]
        - Key: ised-cost-centre
          Value: cio-rdad
        - Key: ised-project-id
          Value: cops-aws
        - Key: ised-environment
          Value: ops
Outputs:
  RoleLambdaExecution:
    Description: LambdaExecutionRole
    Value: !GetAtt LambdaExecutionRole.Arn
    Export: 
      Name: LambdaExecutionRole
  RoleVPCFlowLog:
    Description: VPCFlowLogRole
    Value: !GetAtt VPCFlowLogRole.Arn
    Export: 
      Name: VPCFlowLogRole
  RoleAdmin:
    Condition: IsNotMaster
    Description: IsedAdminRole
    Value: !GetAtt IsedAdminRole.Arn
    Export: 
      Name: IsedAdminRole
  ManagedInstanceProfile:
    Description: ManagedInstanceProfile
    Value: !Ref ManagedInstanceProfile
    Export:
      Name: ManagedInstanceProfile
