AWSTemplateFormatVersion: "2010-09-09"
# Version 1.0 - Initial version
# Version 1.1 - Link to s3 template, use System Manager
Description: Template to create the log S3 Bucket. Version 1.1
Resources:
  S3LogBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "{{resolve:ssm:TemplateS3:1}}"
      Parameters:
        Name: log
        S3BucketPolicy: Local
        S3BucketAccess: LogDeliveryWrite
        KmsArn: NA