AWSTemplateFormatVersion: "2010-09-09"
# Version 1.0 - Initial version
Parameters:
  S3BucketNamePrefix:
    Type: String
  AccountIDLog:
    Type: String
  TemplateS3:
    Type: String
Resources:
  TemplateS3Parameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: TemplateS3
      Type: String
      Value: !Ref TemplateS3
  S3BucketNamePrefixParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: S3BucketNamePrefix
      Type: String
      Value: !Ref S3BucketNamePrefix
  AccountIDLogParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDLog
      Type: String
      Value: !Ref AccountIDLog
