AWSTemplateFormatVersion: "2010-09-09"
# Version 1.0 - Initial version
# Version 1.1 - Added S3 bucket and Cots account parameter.
# Version 1.2 - Added parameter that relate to Jira and AWS Account id
Parameters:
  S3BucketNamePrefix:
    Type: String
  S3BucketVPCFlowLogs:
    Type: String
    Description: The ARN S3 bucket that VPC Flow Logs will be published. 
  AccountIDLog:
    Type: String
  AccountIDCots:
    Type: String    
  AccountIDStudents:
    Type: String       
  AccountIDSandbox:
    Type: String    
  AccountIDSandboxDB:
    Type: String  
  AccountIDAPIStore:
    Type: String  
  AccountIDOpenShift:
    Type: String  
  TemplateS3:
    Type: String
  TemplateRemediationConfig:
    Type: String
  JiraPassRemediation:
    Type: String
    NoEcho: true
  JiraURL:
    Type: String
  JiraUser:
    Type: String
  JiraProject:
    Type: String    
Resources:
  TemplateS3Parameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: TemplateS3
      Type: String
      Value: !Ref TemplateS3
  S3BucketNamePrefixParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: S3BucketNamePrefix
      Type: String
      Value: !Ref S3BucketNamePrefix
  S3BucketVPCFlowLogsParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: S3BucketVPCFlowLogs
      Type: String
      Value: !Ref S3BucketVPCFlowLogs
  AccountIDLogParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDLog
      Type: String
      Value: !Ref AccountIDLog
  AccountIDCOTSParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDCots
      Type: String
      Value: !Ref AccountIDCots
  AccountIDSandboxParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDSandbox
      Type: String
      Value: !Ref AccountIDSandbox     
  AccountIDSandboxDBParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDSandboxDB
      Type: String
      Value: !Ref AccountIDSandboxDB    
  AccountIDStudentsParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDStudents
      Type: String
      Value: !Ref AccountIDStudents      
  AccountIDAPIStoreParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDAPIStore
      Type: String
      Value: !Ref AccountIDAPIStore    
  AccountIDOpenShiftParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDOpenShift
      Type: String
      Value: !Ref AccountIDOpenShift            
  JiraPassRemediationParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: JiraPassRemediation
      Type: String
      Value: !Ref JiraPassRemediation
  JiraURLParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: JiraURL
      Type: String
      Value: !Ref JiraURL
  JiraUserParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: JiraUser
      Type: String
      Value: !Ref JiraUser      
  JiraProjectParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: JiraProject
      Type: String
      Value: !Ref JiraProject    
  TemplateRemediationConfigParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: TemplateRemediationConfig
      Type: String
      Value: !Ref TemplateRemediationConfig      