AWSTemplateFormatVersion: "2010-09-09"
# Version 1.0 - Initial version
# Version 1.1 - Added S3 bucket and Cots account parameter.
Parameters:
  S3BucketNamePrefix:
    Type: String
  S3BucketVPCFlowLogs:
    Type: String
    Description: The S3 bucket that VPC Flow Logs will be published
  AccountIDLog:
    Type: String
  AccountIDCots:
    Type: String    
  TemplateS3:
    Type: String
Resources:
  TemplateS3Parameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: TemplateS3
      Type: String
      Value: !Ref TemplateS3
  S3BucketNamePrefixParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: S3BucketNamePrefix
      Type: String
      Value: !Ref S3BucketNamePrefix
  S3BucketVPCFlowLogsParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: S3BucketVPCFlowLogs
      Type: String
      Value: !Ref S3BucketVPCFlowLogs
  AccountIDLogParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDLog
      Type: String
      Value: !Ref AccountIDLog
  AccountIDCOTSParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDCots
      Type: String
      Value: !Ref AccountIDCots
