AWSTemplateFormatVersion: "2010-09-09"
Description: Add entries to the Parameter Store. Version 1.3
# Version 1.0 - Initial version
# Version 1.1 - Added S3 bucket and Cots account parameter.
# Version 1.2 - Added parameter that relate to Jira and AWS Account id
# Version 1.3 - Added parameters for IT Security and ISED Cloud mailboxes
Parameters:
  IsedCloudEmail:
    Type: String
  ITSecurityEmail:
    Type: String
  S3BucketNamePrefix:
    Type: String
  S3Templates:
    Type: String
  AccountIDMaster:
    Type: String
  AccountIDSharedServices:
    Type: String
  AccountIDSecurity:
    Type: String
  AccountIDLog:
    Type: String
  AccountIDCOTS:
    Type: String    
  AccountIDCOTSDev:
    Type: String    
  AccountIDStudents:
    Type: String       
  AccountIDSandbox:
    Type: String    
  AccountIDSandboxDB:
    Type: String  
  AccountIDAPIStore:
    Type: String  
  AccountIDOpenShift:
    Type: String  
  AccountIDOpenShiftDev:
    Type: String  
  AccountIDOpenShiftLab:
    Type: String  
  AccountIDDB:
    Type: String
  AccountIDTbsCpiaDev:
    Type: String
  AccountEmailTbsCpiaDev:
    Type: String
  AccountEmailProjects01:
    Type: String
  AccountEmailDB:
    Type: String
  AccountEmailStudents:
    Type: String
  AccountEmailSandbox:
    Type: String
  AccountEmailAPIStore:
    Type: String
  AccountEmailLog:
    Type: String
  AccountIDDBDev:
    Type: String
  AccountEmailSecurity:
    Type: String
  AccountEmailSecurityDev:
    Type: String
  AccountEmailSharedServices:
    Type: String
  AccountEmailOpenShift:
    Type: String
  AccountEmailOpenShiftLab:
    Type: String
  AccountEmailSandboxDB:
    Type: String
  AccountIDSecurityDev:
    Type: String
  AccountEmailCOTSDev:
    Type: String
  AccountEmailDBDev:
    Type: String
  AccountEmailCOTS:
    Type: String
  AccountIDProjects01:
    Type: String
  JiraPassRemediation:
    Type: String
    NoEcho: true
  JiraURL:
    Type: String
  JiraUser:
    Type: String
  JiraProject:
    Type: String    
Resources:
  S3BucketNamePrefixParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: S3BucketNamePrefix
      Type: String
      Value: !Ref S3BucketNamePrefix
  AccountIDMasterParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDMaster
      Type: String
      Value: !Ref AccountIDMaster
  AccountIDSharedServicesParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDSharedServices
      Type: String
      Value: !Ref AccountIDSharedServices
  AccountIDSecurityParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDSecurity
      Type: String
      Value: !Ref AccountIDSecurity
  AccountIDLogParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDLog
      Type: String
      Value: !Ref AccountIDLog
  AccountIDCOTSParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDCOTS
      Type: String
      Value: !Ref AccountIDCOTS
  AccountIDCOTSDevParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDCOTSDev
      Type: String
      Value: !Ref AccountIDCOTSDev
  AccountIDSandboxParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDSandbox
      Type: String
      Value: !Ref AccountIDSandbox     
  AccountIDSandboxDBParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDSandboxDB
      Type: String
      Value: !Ref AccountIDSandboxDB    
  AccountIDStudentsParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDStudents
      Type: String
      Value: !Ref AccountIDStudents      
  AccountIDAPIStoreParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDAPIStore
      Type: String
      Value: !Ref AccountIDAPIStore    
  AccountIDOpenShiftParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDOpenShift
      Type: String
      Value: !Ref AccountIDOpenShift
  AccountIDOpenShiftDevParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDOpenShiftDev
      Type: String
      Value: !Ref AccountIDOpenShiftDev
  AccountIDOpenShiftLabParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDOpenShiftLab
      Type: String
      Value: !Ref AccountIDOpenShiftLab
  JiraPassRemediationParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: JiraPassRemediation
      Type: String
      Value: !Ref JiraPassRemediation
  JiraURLParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: JiraURL
      Type: String
      Value: !Ref JiraURL
  JiraUserParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: JiraUser
      Type: String
      Value: !Ref JiraUser      
  JiraProjectParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: JiraProject
      Type: String
      Value: !Ref JiraProject    
  IsedCloudEmailParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: IsedCloudEmail
      Type: String
      Value: !Ref IsedCloudEmail
  ITSecurityEmailParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: ITSecurityEmail
      Type: String
      Value: !Ref ITSecurityEmail
  S3TemplatesParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: S3Templates
      Type: String
      Value: !Ref S3Templates


  AccountIDDBParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDDB
      Type: String
      Value: !Ref AccountIDDB
  AccountEmailProjects01Parameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountEmailProjects01
      Type: String
      Value: !Ref AccountEmailProjects01
  AccountEmailDBParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountEmailDB
      Type: String
      Value: !Ref AccountEmailDB
  AccountEmailStudentsParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountEmailStudents
      Type: String
      Value: !Ref AccountEmailStudents
  AccountEmailSandboxParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountEmailSandbox
      Type: String
      Value: !Ref AccountEmailSandbox
  AccountEmailAPIStoreParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountEmailAPIStore
      Type: String
      Value: !Ref AccountEmailAPIStore
  AccountEmailLogParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountEmailLog
      Type: String
      Value: !Ref AccountEmailLog
  AccountIDDBDevParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDDBDev
      Type: String
      Value: !Ref AccountIDDBDev
  AccountIDTbsCpiaDevParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDTbsCpiaDev
      Type: String
      Value: !Ref AccountIDTbsCpiaDev
  AccountEmailTbsCpiaDevParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountEmailTbsCpiaDev
      Type: String
      Value: !Ref AccountEmailTbsCpiaDev
  AccountEmailSecurityParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountEmailSecurity
      Type: String
      Value: !Ref AccountEmailSecurity
  AccountEmailSecurityDevParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountEmailSecurityDev
      Type: String
      Value: !Ref AccountEmailSecurityDev
  AccountEmailSharedServicesParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountEmailSharedServices
      Type: String
      Value: !Ref AccountEmailSharedServices
  AccountEmailOpenShiftParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountEmailOpenShift
      Type: String
      Value: !Ref AccountEmailOpenShift
  AccountEmailOpenShiftLabParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountEmailOpenShiftLab
      Type: String
      Value: !Ref AccountEmailOpenShiftLab
  AccountEmailSandboxDBParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountEmailSandboxDB
      Type: String
      Value: !Ref AccountEmailSandboxDB
  AccountIDSecurityDevParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDSecurityDev
      Type: String
      Value: !Ref AccountIDSecurityDev
  AccountEmailCOTSDevParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountEmailCOTSDev
      Type: String
      Value: !Ref AccountEmailCOTSDev
  AccountEmailDBDevParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountEmailDBDev
      Type: String
      Value: !Ref AccountEmailDBDev
  AccountEmailCOTSParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountEmailCOTS
      Type: String
      Value: !Ref AccountEmailCOTS
  AccountIDProjects01Parameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDProjects01
      Type: String
      Value: !Ref AccountIDProjects01
