AWSTemplateFormatVersion: "2010-09-09"
# Version 1.0 - Initial version
# Version 1.1 - Added S3 bucket and Cots account parameter.
Parameters:
  S3BucketNamePrefix:
    Type: String
  S3BucketVPCFlowLogs:
    Type: String
    Description: The ARN S3 bucket that VPC Flow Logs will be published. 
  AccountIDLog:
    Type: String
  AccountIDCots:
    Type: String    
  AccountIDStudents:
    Type: String       
  AccountIDSandbox:
    Type: String    
  AccountIDSandboxDB:
    Type: String  
  AccountIDAPIStore:
    Type: String  
  AccountIDOpenShift:
    Type: String  
  TemplateS3:
    Type: String
  TemplateRemediationConfig:
    Type: String
  JiraPassRemediation:
    Type: String
    NoEcho: true
  JiraURL:
    Type: String
  JiraUser:
    Type: String
Resources:
  TemplateS3Parameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: TemplateS3
      Type: String
      Value: !Ref TemplateS3
  S3BucketNamePrefixParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: S3BucketNamePrefix
      Type: String
      Value: !Ref S3BucketNamePrefix
  S3BucketVPCFlowLogsParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: S3BucketVPCFlowLogs
      Type: String
      Value: !Ref S3BucketVPCFlowLogs
  AccountIDLogParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDLog
      Type: String
      Value: !Ref AccountIDLog
  AccountIDCOTSParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDCots
      Type: String
      Value: !Ref AccountIDCots
  AccountIDSandboxParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDCots
      Type: String
      Value: !Ref AccountIDCots     
  AccountIDSandboxDBParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDCots
      Type: String
      Value: !Ref AccountIDCots    
  AccountIDStudentsParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDCots
      Type: String
      Value: !Ref AccountIDCots      
  AccountIDAPIStoreParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDCots
      Type: String
      Value: !Ref AccountIDCots    
  AccountIDOpenShiftParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: AccountIDCots
      Type: String
      Value: !Ref AccountIDCots            
  JiraPassRemediationParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: ised-jira-password2
      Type: String
      Value: !Ref JiraPassRemediation
